security:
    encoders:
        App\Entity\User:
            algorithm: bcrypt
    providers:
        basic_provider:
            entity:
                class: App\Entity\User
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            request_matcher: App\Security\RequestMatcher
            anonymous: true
            lazy: true
            provider: basic_provider
            stateless: true
            guard:
                authenticators:
                    - App\Security\Authenticator
