name: phpunit
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: start mysql
        run: sudo service mysql start
      - name: Install dependencies
        run: composer install --prefer-dist --no-progress --no-suggest
      - name: create database
        run: php bin/console doctrine:database:create
      - name: test
        run: php bin/console doctrine:query:sql 'show tables'
      - name: PHPUnit
        uses: chindit/actions-phpunit-symfony@master
